Bug #50461: Fix ordering of comparision to None
The test test_generic/test_dispatch fails with exception:

File "/usr/lib/python3/dist-packages/notifier/nf_generic.py", line 223, in step
    if __min_timer and (__min_timer < timeout or timeout is None):
TypeError: unorderable types: int() < NoneType()