Bug #50461: Add test with no timeout
The folowing exception was found:

    File "/usr/lib/python3/dist-packages/notifier/nf_generic.py", line 223, in step
        if __min_timer and (__min_timer < timeout or timeout is None):
    TypeError: unorderable types: int() < NoneType()

The test suite now can reproduce this error